#!/usr/bin/bash
## This script is under license BEER-WARE.
# "THE BEER-WARE LICENSE" (Revision 42):
# <eric@obarun.org> wrote this file.  As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return.   Eric Vidal

# functions file for obarun-mkiso package

## 		Some global variables needed

HOME_PATH="/var/lib/obarun/obarun-mkiso"
MAKE_ISO="/usr/lib/obarun/make_iso"
BUILD_ISO="/usr/lib/obarun/build_iso"
WORK_DIR="${HOME_PATH}/work"
ARCH=$(uname -m)
PKG_LIST=""


clean_install(){
	
	echo_display " Cleaning up"
	if [[ $(mount | grep "$NEWROOT"/proc) ]]; then
		echo_valid " Umount $NEWROOT"
		mount_umount "$NEWROOT" "umount"
	fi
	if [[ $(mount | grep "$WORK_DIR/airootfs/proc") ]]; then
		echo_valid " Umount $WORK_DIR/airootfs"
		mount_umount "$WORK_DIR/airootfs" "umount"
	fi
	if [[ $(awk -F':' '{ print $1}' /etc/passwd | grep usertmp) >/dev/null ]]; then
		echo_valid " Removing user usertmp"
		user_del "usertmp" &>/dev/null
	fi
	
	echo_valid " Restore your shell options"
	shellopts_restore

	exit
}

define_iso_variable(){
	local msg variable set
	msg="$1"
	variable="$2"
	
	echo_display " Enter the $msg"
	read -e set
	
	while [[ -z $set ]]; do
		echo_retry " Empty value, please retry"
		read set
	done
	
	case $variable in
		ISO_NAME)
			ISO_NAME="${set}"
			echo_valid " ${msg} is now : $set"
			sed -i "s,ISO_NAME=.*$,ISO_NAME=\"${set}\",g" /etc/obarun/mkiso.conf;;
		ISO_VERSION)
			ISO_VERSION="${set}"
			echo_valid " ${msg} is now : $set"
			sed -i "s,ISO_VERSION=.*$,ISO_VERSION=\"${set}\",g" /etc/obarun/mkiso.conf;;
		ISO_LABEL)
			ISO_LABEL="${set}"
			echo_valid " ${msg} is now : $set"
			sed -i "s,ISO_LABEL=.*$,ISO_LABEL=\"${set}\",g" /etc/obarun/mkiso.conf;;
		ISO_PUBLISHER)
			ISO_PUBLISHER="${set}"
			echo_valid " ${msg} is now : $set"
			sed -i "s,ISO_PUBLISHER=.*$,ISO_PUBLISHER=\"${set}\",g" /etc/obarun/mkiso.conf;;
		ISO_APPLICATION)
			ISO_APPLICATION="${set}"
			echo_valid " ${msg} is now : $set"
			sed -i "s,ISO_APPLICATION=.*$,ISO_APPLICATION=\"${set}\",g" /etc/obarun/mkiso.conf;;
		INSTALL_DIR)
			INSTALL_DIR="${set}"
			echo_valid " ${msg} is now : $set"
			sed -i "s,INSTALL_DIR=.*$,INSTALL_DIR=\"${set}\",g" /etc/obarun/mkiso.conf;;
		OUT_DIR)
			OUT_DIR="${set}"
			echo_valid " ${msg} is now : $set"
			sed -i "s,OUT_DIR=.*$,OUT_DIR=\"${set}\",g" /etc/obarun/mkiso.conf;;
		IMAGE_MODE)
			while [[ $set != @(img|sfs) ]]; do
				echo_retry " sfs_mode must be img or sfs, please retry"
				read set
			done
			IMAGE_MODE="${set}"
			echo_valid " ${msg} is now : $set"
			sed -i "s,IMAGE_MODE=.*$,IMAGE_MODE=\"${set}\",g" /etc/obarun/mkiso.conf;;
		SFS_COMP)
			while [[ $set != @(gzip|lzma|lzo|xz) ]]; do
				echo_retry " sfs_comp must be gzip or lzma or lzo or xz, please retry"
				read set
			done
			SFS_COMP="${set}"
			echo_valid " ${msg} is now : $set"
			sed -i "s,SFS_COMP=.*$,SFS_COMP=\"${set}\",g" /etc/obarun/mkiso.conf;;
		VERBOSE)
			reply_answer
			if (( ! $? )); then
				VERBOSE="yes"
				d_verbose="-v"
				echo_valid " Verbose enabled"
				sed -i "s,VERBOSE=.*$,VERBOSE=\"yes\",g" /etc/obarun/mkiso.conf
			else
				VERBOSE="no"
				unset d_verbose
				echo_notvalid " Verbose disabled"
				sed -i "s,VERBOSE=.*$,VERBOSE=\"no\",g" /etc/obarun/mkiso.conf
			fi;;
	esac
}

start_build(){
	local _package
	echo_display " Check packages needed for the script"
	
	for _package in squashfs-tools libisoburn gzip; do
		if [[ ! $(pacman -Qs $_package) >/dev/null ]]; then
			echo_notvalid " Installing $_package"
			pacman -S $_package --config "$PAC_CONF" --cachedir "$CACHE_DIR" || die " Impossible to install the package squashfs-tools" "clean_install"
		else
			echo_valid " $_package : already installed"
		fi
	done
	
	unset _package	
	
	check_mountpoint "$NEWROOT"
	
	if (( $? )); then
		echo_retry " This is not a valid mountpoint"
		die " You need to mount a device on $NEWROOT or choose another directory" "clean_install"
	fi
	
	${BUILD_ISO} ${VERBOSE}
}

clean_work_dir(){
	if [[ -d $WORK_DIR ]]; then
		echo_display " Removing $WORK_DIR"
		rm -R "$WORK_DIR"
	else
		echo_display " $WORK_DIR doesn't exist"
	fi
}

## 		Select root directory

choose_rootdir(){	
	local _directory
		
	echo_display " Enter your root directory :"
	read -e _directory
		
	until [[ -d "$_directory" ]]; do
		echo_retry " This is not a directory, please retry :"
		read -e _directory
	done
	
	while ! mountpoint -q "$_directory"; do
		echo_retry " This is not a valide mountpoint, please retry :"
		read -e _directory
	done

	echo_valid " Your root directory for installation is now : $_directory"
	#NEWROOT="${_directory}"
	sed -i "s,NEWROOT=.*$,NEWROOT=\"${_directory}\",g" /etc/obarun/mkiso.conf
	
	unset _directory
}

main_menu(){
	
	local step=100

while [[ "$step" !=  15 ]]; do
	clear
	echo_bold ""
	echo_bold ""
	echo_info_menu "**************************************************************"
	echo_info_menu "                       Iso menu"
	echo_info_menu "**************************************************************"
	echo_bold ""
	echo_bold " 1  -  Choose directory to copy on iso ${green}[$NEWROOT]"
	echo_bold " 2  -  Set iso name ${green}[$ISO_NAME]"
	echo_bold " 3  -  Set iso version ${green}[$ISO_VERSION]"
	echo_bold " 4  -  Set iso label ${green}[$ISO_LABEL]"
	echo_bold " 5  -  Set iso publisher ${green}[$ISO_PUBLISHER]"
	echo_bold " 6  -  Set application name for the iso ${green}[$ISO_APPLICATION]"
	echo_bold " 7  -  Set installation directory inside iso ${green}[$INSTALL_DIR]"
	echo_bold " 8  -  Set directory where the iso is saved ${green}[$OUT_DIR]"
	echo_bold " 9  -  Set SquashFS image mode (img or sfs) ${green}[$IMAGE_MODE]"
	echo_bold " 10 -  Set SquashFS compression type (gzip, lzma, lzo, xz) ${green}[$SFS_COMP]"
	echo_bold ""
	echo_bold " 11 -  Start building"
	echo_bold ""
	echo_info_menu "**************************************************************"
	echo_info_menu "                      Expert mode"
	echo_info_menu "**************************************************************"
	echo_bold ""
	echo_bold " 12 -  Enable verbose ${green}[$VERBOSE]"
	echo_bold " 13 -  Clean the working directory ${green}[$WORK_DIR]"
	echo_bold " 14 -  Take a coffee"
	echo_bold ""
	echo_bold ""
	echo_bold " ${red}15  -  Exit from mkiso script"
	echo_bold ""
	echo_bold ""
	echo_display " Enter your choice :";read  step

		case "$step" in 
			1)	choose_rootdir;;
			2)	define_iso_variable "iso name" "ISO_NAME";; 
			3)	define_iso_variable "iso version" "ISO_VERSION";; 
			4)	define_iso_variable "iso label" "ISO_LABEL";; 
			5)	define_iso_variable "iso publisher" "ISO_PUBLISHER";; 
			6)	define_iso_variable "application name" "ISO_APPLICATION";;
			7)	define_iso_variable "installation directory" "INSTALL_DIR";; 
			8)	define_iso_variable "output directory" "OUT_DIR";; 
			9)	define_iso_variable "image mode [img|sfs]" "IMAGE_MODE";; 
			10)	define_iso_variable "compression type [gzip|lzma|lzo|xz]" "SFS_COMP";; 
			11)	echo_display " Start building iso"
				start_build
				exit;;
			12) define_iso_variable "option for verbosity [y|n]" "VERBOSE";;	
			13) clean_work_dir;;
			14) echo_info " Under development, not available";;
			15)	exit;;
			*) echo_retry " Invalid number, please retry:"
		esac
		echo_info " Press enter to return to the iso menu"
		read enter 
done
}

